# Generated by Django 2.1.7 on 2019-08-13 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.IntegerField()),
                ('universty', models.CharField(max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('person_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('sex', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('locating_city', models.CharField(blank=True, max_length=10, null=True)),
                ('work_or_study', models.CharField(blank=True, choices=[('w', 'word'), ('s', 'study')], max_length=10, null=True)),
                ('graduation_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CDapp.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10)),
                ('capital_city', models.CharField(default='', max_length=10)),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='locating_province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CDapp.Province'),
        ),
    ]
