# Generated by Django 2.1.7 on 2019-08-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CDapp', '0002_auto_20190813_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='sex',
        ),
        migrations.AddField(
            model_name='person',
            name='position',
            field=models.CharField(default='', max_length=10),
        ),
    ]
