# Generated by Django 2.1.7 on 2019-08-19 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CDapp', '0005_person_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='avatar',
            field=models.ImageField(default='', upload_to='%Y/%m/%d/'),
        ),
    ]
