# Generated by Django 2.1.7 on 2019-08-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CDapp', '0007_auto_20190819_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='upload_image/%Y-%m-%d/'),
        ),
    ]
