# Generated by Django 2.1.7 on 2019-08-19 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CDapp', '0008_auto_20190819_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d/'),
        ),
    ]
