# Generated by Django 2.1.7 on 2019-08-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CDapp', '0009_auto_20190819_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='avatar_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
