# Generated by Django 2.1.7 on 2019-08-21 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CDapp', '0010_person_avatar_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='avatar_url',
        ),
    ]
